# Generated by Django 3.0.2 on 2020-03-13 03:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='项目名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('svn', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='SVN 地址')),
                ('build', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Build 脚本参数')),
                ('member', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name=' 项目成员')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ('add_time',),
            },
        ),
        migrations.CreateModel(
            name='RomImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.FileField(blank=True, null=True, upload_to='uploads/images/rom/%Y/%m/%d/', verbose_name='image')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='文件描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': 'RomImage',
                'verbose_name_plural': 'RomImage',
                'ordering': ('add_time',),
            },
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMC_ip', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='BMC IP 地址')),
                ('Host_ip', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Host IP 地址')),
                ('web_username', models.CharField(blank=True, default='admin', max_length=100, null=True, verbose_name='Web 用户名')),
                ('web_password', models.CharField(blank=True, default='admin', max_length=100, null=True, verbose_name='Web 密码')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='机器信息描述')),
                ('current_state', models.IntegerField(choices=[(1, '空闲'), (2, '使用中(可查看,请勿操作)'), (3, '占用中,勿动')], default=1, verbose_name='机器状态')),
                ('end_time', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='结束时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': 'MachineInfo',
                'verbose_name_plural': 'MachineInfo',
            },
        ),
    ]
