# Generated by Django 3.0.2 on 2020-03-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineinfo',
            name='setting_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='起始时间'),
        ),
    ]
