# Generated by Django 3.0.2 on 2020-01-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('add_time',), 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
