# Generated by Django 3.0.2 on 2020-01-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200113_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='member',
        ),
    ]
