# Generated by Django 3.0.2 on 2020-02-09 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20200113_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.FileField(blank=True, null=True, upload_to='uploads/images/rom/%Y/%m/%d/', verbose_name='image')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='文件描述')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': 'RomImage',
                'verbose_name_plural': 'RomImage',
                'ordering': ('add_time',),
            },
        ),
    ]
