# Generated by Django 3.0.2 on 2020-03-14 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200313_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 5, 35, 32, 684654), verbose_name='添加时间'),
        ),
    ]
