# Generated by Django 3.0.2 on 2020-03-25 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200314_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 7, 0, 9, 316497, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
