# Generated by Django 3.0.2 on 2020-02-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200210_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='web_password',
            field=models.CharField(blank=True, default='admin', max_length=100, null=True, verbose_name='Web 密码'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='web_username',
            field=models.CharField(blank=True, default='admin', max_length=100, null=True, verbose_name='Web 用户名'),
        ),
    ]
