# Generated by Django 3.0.2 on 2020-02-10 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_auto_20200210_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineinfo',
            name='build',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='svn',
        ),
        migrations.AddField(
            model_name='project',
            name='build',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Build 脚本参数'),
        ),
        migrations.AddField(
            model_name='project',
            name='svn',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='SVN 地址'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
