# Generated by Django 3.0.2 on 2020-03-30 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200330_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='current_state',
            field=models.IntegerField(choices=[(1, '空闲'), (2, '使用中(可查看,请勿操作)'), (3, '占用中,勿动')], default=1, verbose_name='机器状态'),
        ),
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 6, 54, 33, 30096, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
