# Generated by Django 3.0.2 on 2020-03-30 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200330_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 12, 28, 49, 407258, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
