# Generated by Django 3.0.2 on 2020-04-01 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200330_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='romimagefile',
            name='release_note',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images/rom/%Y/%m/%d/release_note/', verbose_name='releaseNote'),
        ),
        migrations.AddField(
            model_name='romimagefile',
            name='release_note_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 7, 20, 19, 199951, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='romimagefile',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images/rom/%Y/%m/%d/', verbose_name='镜像文件'),
        ),
    ]
