# Generated by Django 3.0.2 on 2020-04-01 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200401_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 8, 54, 51, 221245, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='romimagefile',
            name='release_note',
            field=models.FileField(blank=True, null=True, upload_to=project.models.release_note_path, verbose_name='releaseNote'),
        ),
        migrations.AlterField(
            model_name='romimagefile',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=project.models.rom_path, verbose_name='镜像文件'),
        ),
    ]
