# Generated by Django 3.0.2 on 2020-04-09 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200401_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 11, 25, 43, 494656, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
