# Generated by Django 3.0.2 on 2020-04-10 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20200410_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 2, 2, 10, 845286, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
