# Generated by Django 3.0.2 on 2020-04-18 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200413_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 56, 36, 347829, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
