# Generated by Django 3.0.2 on 2020-04-18 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20200418_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 57, 54, 414175, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
