# Generated by Django 3.0.2 on 2020-04-22 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200422_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 7, 33, 9, 366620, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
