# Generated by Django 3.0.2 on 2020-05-03 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20200422_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romimagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 15, 15, 13, 490548, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
