# Generated by Django 3.0.2 on 2020-02-22 07:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'ResourceType',
                'verbose_name_plural': 'ResourceType',
                'ordering': ('add_time',),
            },
        ),
        migrations.CreateModel(
            name='CloundResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='项目名')),
                ('url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='网盘 地址')),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='文件描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='support.ResourceType', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '教程资源',
                'verbose_name_plural': '教程资源',
                'ordering': ('add_time',),
            },
        ),
    ]
