# Generated by Django 3.0.2 on 2020-02-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ('add_time',), 'verbose_name': '资源类型', 'verbose_name_plural': '资源类型'},
        ),
    ]
