# Generated by Django 3.0.2 on 2020-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200222_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloundresource',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='资源名'),
        ),
    ]
