# Generated by Django 3.0.2 on 2020-02-23 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0005_websitelink_websitetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ('add_time',), 'verbose_name': '网站类型', 'verbose_name_plural': '网站类型'},
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人员'),
        ),
        migrations.AddField(
            model_name='websitetype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人员'),
        ),
    ]
