# Generated by Django 3.0.2 on 2020-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20200223_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelink',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='网站描述'),
        ),
    ]
