# Generated by Django 3.0.2 on 2020-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20200223_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloundresource',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='文件描述'),
        ),
    ]
