# Generated by Django 3.0.2 on 2020-02-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelink',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='support.WebSiteLink'),
        ),
    ]
