# Generated by Django 3.0.2 on 2020-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_websitelink_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitelink',
            name='parent',
        ),
        migrations.AddField(
            model_name='websitelink',
            name='likely',
            field=models.ManyToManyField(blank=True, null=True, related_name='_websitelink_likely_+', to='support.WebSiteLink', verbose_name='相似文章'),
        ),
    ]
