# Generated by Django 3.0.2 on 2020-02-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_auto_20200224_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitelink',
            name='likely',
        ),
    ]
