# Generated by Django 3.0.2 on 2020-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_remove_websitelink_likely'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelink',
            name='Public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
