# Generated by Django 3.0.2 on 2020-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_websitelink_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetype',
            name='order',
            field=models.IntegerField(default='1', verbose_name='排序索引'),
        ),
    ]
