# Generated by Django 3.0.2 on 2020-02-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_websitetype_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitelink',
            old_name='Public',
            new_name='public',
        ),
    ]
