# Generated by Django 3.0.2 on 2020-02-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20200224_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ('order',), 'verbose_name': '网站类型', 'verbose_name_plural': '网站类型'},
        ),
    ]
