# Generated by Django 3.0.2 on 2020-03-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0022_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='current_state',
            field=models.IntegerField(choices=[(1, '待实现'), (2, '已实现'), (3, '已拒绝')], default=1, verbose_name='机器状态'),
        ),
    ]
