# Generated by Django 3.0.2 on 2020-03-30 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0023_demand_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='current_state',
            field=models.IntegerField(choices=[(1, '待实现'), (2, '已实现'), (3, '已拒绝')], default=1, verbose_name='当前状态'),
        ),
    ]
