# Generated by Django 3.0.2 on 2020-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0025_auto_20200330_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='current_state',
            field=models.IntegerField(choices=[(0, '待实现'), (1, '已实现'), (2, '已拒绝')], default=0, verbose_name='当前状态'),
        ),
    ]
