# Generated by Django 3.0.2 on 2020-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0026_auto_20200330_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='需求描述'),
        ),
    ]
