# Generated by Django 3.0.2 on 2020-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_auto_20200330_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='last_edit_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
