# Generated by Django 3.0.2 on 2020-03-30 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0030_auto_20200330_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='保存日期'),
        ),
    ]
