# Generated by Django 3.0.2 on 2020-04-10 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_auto_20200410_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': '笔记本', 'verbose_name_plural': '笔记本'},
        ),
        migrations.AddField(
            model_name='note',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='note',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
