# Generated by Django 3.0.2 on 2020-04-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0005_auto_20200410_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale',
            name='browse_num',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
