# Generated by Django 3.0.2 on 2020-04-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0008_articletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articals.ArticleType', verbose_name='父分类'),
        ),
    ]
