# Generated by Django 3.0.2 on 2020-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0009_auto_20200422_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='articals.ArticleType', verbose_name='文章分类'),
        ),
    ]
