# Generated by Django 3.0.2 on 2020-05-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0010_articale_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articale',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articals.Note', verbose_name='笔记本'),
        ),
        migrations.AlterField(
            model_name='articale',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='articals.ArticleType', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分类名'),
        ),
        migrations.AlterUniqueTogether(
            name='articletype',
            unique_together={('name', 'parent')},
        ),
    ]
